openapi: 3.0.0
info:
  title: Note Taking API
  description: API for a Note Taking application
  version: 1.0.0
servers:
  - url: http://localhost:3000 # Update with your API server URL

paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Bad request

  /api/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: Unauthorized

  /api/notes:
    get:
      summary: Retrieve all notes
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of notes
        '401':
          description: Unauthorized

    post:
      summary: Create a new note
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Note created successfully
        '401':
          description: Unauthorized

  /api/notes/{id}:
    get:
      summary: Retrieve a specific note by ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the note to retrieve
      responses:
        '200':
          description: Note retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: Note not found

    put:
      summary: Update a specific note by ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the note to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Note updated successfully
        '401':
          description: Unauthorized
        '404':
          description: Note not found

    delete:
      summary: Delete a specific note by ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the note to delete
      responses:
        '204':
          description: Note deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Note not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer